### ISSUE TITLE
/v1/api/images 接口在没有图片上传的时候会抛出错误

### ISSUE THREAD

**Issue by Jiang-Xuan** [Jiang-Xuan/tuchuang.space#79]
导致后端进程崩溃

```plaintext
2019-12-19 18:29 +08:00: TypeError: Cannot read property 'map' of undefined
2019-12-19 18:29 +08:00:     at VersionOneApiRouter.route.post (/var/www/production/source/backend/version_one_api_router/index.js:123:42)
2019-12-19 18:29 +08:00:     at Layer.handle [as handle_request] (/var/www/production/source/backend/node_modules/express/lib/router/layer.js:95:5)
2019-12-19 18:29 +08:00:     at next (/var/www/production/source/backend/node_modules/express/lib/router/route.js:137:13)
2019-12-19 18:29 +08:00:     at uploadMiddleware (/var/www/production/source/backend/version_one_api_router/index.js:100:5)
2019-12-19 18:29 +08:00:     at Immediate.<anonymous> (/var/www/production/source/backend/node_modules/multer/lib/make-middleware.js:53:37)
2019-12-19 18:29 +08:00:     at runCallback (timers.js:706:11)
2019-12-19 18:29 +08:00:     at tryOnImmediate (timers.js:676:5)
2019-12-19 18:29 +08:00:     at processImmediate (timers.js:658:5)
2019-12-19 18:39 +08:00: TypeError: Cannot read property 'map' of undefined
2019-12-19 18:39 +08:00:     at VersionOneApiRouter.route.post (/var/www/production/source/backend/version_one_api_router/index.js:123:42)
2019-12-19 18:39 +08:00:     at Layer.handle [as handle_request] (/var/www/production/source/backend/node_modules/express/lib/router/layer.js:95:5)
2019-12-19 18:39 +08:00:     at next (/var/www/production/source/backend/node_modules/express/lib/router/route.js:137:13)
2019-12-19 18:39 +08:00:     at uploadMiddleware (/var/www/production/source/backend/version_one_api_router/index.js:100:5)
2019-12-19 18:39 +08:00:     at Immediate.<anonymous> (/var/www/production/source/backend/node_modules/multer/lib/make-middleware.js:53:37)
2019-12-19 18:39 +08:00:     at runCallback (timers.js:706:11)
2019-12-19 18:39 +08:00:     at tryOnImmediate (timers.js:676:5)
2019-12-19 18:39 +08:00:     at processImmediate (timers.js:658:5)
```

引起报错的代码是

```js
const { images } = req.files
      if (!images) {
        // 抛出错误
      }
```

没有处理接口传递的数据 images 并不是图片, 也就是 images 为 undefined 的情况

## 如何测试这个 bug

```js
it('images 参数缺失抛出 422 状态码, 错误信息为 { errorMsg: 'images 参数缺失' }', async () => {
  const res = await request(app)
    .post('/api/v1/images')
    .field('images', 'string, not file')
    
  expect(res.status).toEqual(422)
  expect(res.body).toEqual({ errorMsg: 'image 参数缺失' })
})
```

**Comment by Jiang-Xuan** [comment]
视为 client 缺失了 images 参数, http status code 使用 422 https://stackoverflow.com/questions/3050518/what-http-status-response-code-should-i-use-if-the-request-is-missing-a-required
